all:
	cd ..; python wallmapper.py --zoom 8 --basemap mapbox.control-room --output examples/control-room-8.png
	cd ..; python wallmapper.py --zoom 18 --basemap eleanor.mnyzxgvi --output examples/eleanor-woodcut-18.png
	cd ..; python wallmapper.py --zoom 16 --basemap mapbox.dc-nightvision --output examples/dc-nightvision-16.png
	cd ..; python wallmapper.py --zoom 18 --basemap examples.map-vyofok3q --output examples/streets-18.png
	cd ..; python wallmapper.py --zoom 18 --basemap examples.map-9ijuk24y --output examples/terrain-18.png
	cd ..; python wallmapper.py --zoom 18 --basemap examples.map-qfyrx5r8 --output examples/satellite-18.png
	cd ..; python wallmapper.py --zoom 18 --basemap eleanor.ipncow29 --output examples/space-station-18.png
